Feat implement proposal cost and min rep
SecureSECODAO/dao-webapp pull request #106
Opened 2023-06-01 16:50 UTC by BenjaminMeijs

[Summary of the change]

# Changes

- [x] Added useFacetFetch hook
- [ ] replaced useVotingSettings with a useFacetFetch implementation
- [ ] replaced useTimeClaimable with a useFacetFetch implementation
- [ ] added propocal cost and minimum rep to the confirmation page of new proposal form

2023-06-01 21:06 UTC, ThijnK requested changes
There's some very minor stuff

2023-06-01 21:06 UTC, ThijnK commented on src/components/newProposal/steps/Confirmation.tsx
> +              Creating a proposal costs{' '}
I would personally prefer "You will pay X SECOREP"
But I leave it up to you if you actually choose to replace this with it

2023-06-01 21:06 UTC, ThijnK commented on src/components/newProposal/steps/Voting.tsx
> +  const minDuration = minDurationBN?.toNumber() ?? null;
Same as I mentioned above. Maybe we ought to actually catch possible errors with the `toNumber()` conversion

2023-06-01 21:22 UTC, ThijnK approved these changes
Applied my own feedback already
Love the `useFacetFetch` hook, good stuff

2023-06-02 13:21 UTC, ThijnK approved these changes
Already approved above

2023-06-02 14:38 UTC, BenjaminMeijs commented
@ThijnK  I've added some extra stuff:
- added useTier hook
- added useTieredTimeClaimable hook
- changed useFacetFetch to allow for context (extra powerfull stuff)
- added a simple progress bar to the ClaimDailyReward card. Due to SDK issues I could not yet test this. Perhaps remove in the future

2023-06-02 14:51 UTC, ThijnK requested changes
See comment below

2023-06-02 14:51 UTC, ThijnK commented on src/components/dashboard/ClaimDailyRewardCard.tsx
Looking at the progress bar in the UI, I feel like it might be confusing to users. What is it? What do it meaaan?
I  imagine many people would assume something like it being a progress bar counting down to the next claim moment (which in a way is true), but actually (afaik) it's a buildup to the max that you can have stashed for claiming.

What I'm getting at is that we should probably add some text or something that indicated that it is a counter of how many days worth of daily rewards you have available for claiming

2023-06-02 14:51 UTC, ThijnK commented on src/hooks/useTier.ts
> +export const useTier = () => {
Can we have a comment here to explain what this hook is?

The other hooks in useFacetFetch.tsx I feel speak for themselves mostly, but this one's a bit less trivial (at least to me)

2023-06-02 15:33 UTC, merged