Deposit pools
SecureSECODAO/dao-webapp pull request #145
Opened 2023-06-19 18:50 UTC by BenjaminMeijs

Implemented the ability to send SECOIN to a specific pool.
To achieve this, a large part of the code has been refactored and put under the new useDepositAssets hook.

2023-06-19 21:46 UTC, Hidde-Heijnen requested changes
I can select other tokens than Secoin when using the mining of verification pool. It would make sense to me when one of those pools get selected, Secoin get's automatically selected, and that token dropdown get's disabled. I would also put the pool dropdown on top, then disabling the second one makes more sense. Also make sure to double check that it is secoin on submit for those pools, since people can un-disable the dropdown in f12 otherwise

2023-06-20 12:58 UTC, Hidde-Heijnen submitted a review, later dismissed
LGTM

2023-06-20 13:22 UTC, ThijnK commented on src/components/proposal/actions/ApproveSpendingAction.tsx
> +const useTokenInfo = (contractAddress: string) => {
Extract to separate file and use in WithdrawAction.tsx as well

2023-06-20 21:12 UTC, ThijnK approved these changes

2023-06-20 21:12 UTC, merged